language: erlang
otp_release:
  - 20.3
install:
  - make
  - ./rebar3 update
before_script:
  - epmd -daemon
script:
  - make test
  - make xref
  - make dialyzer
  - make demers-direct-mail-test
  - make demers-direct-mail-acked-test
  - make demers-anti-entropy-test
  - make demers-rumor-mongering-test
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
  webhooks: 
      urls:
          - https://webhooks.gitter.im/e/1382c852fbaf2633033a
sudo: required
